### ISSUE TITLE
Cannot log in to Spotify.

### ISSUE THREAD

**Issue by scapehips** [mitchhymel/MusicBeeSyncToService#2]
When I press log in. It says

Opening browser to log in to Spotify...
Could not load file or assembly 'Unosquare.Labs.EmbedIO, Version=2.9.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by mitchhymel** [comment]
I'm not sure why some users see this error. 

The Spotify library this plugin uses has EmbedIO as a dependency, so I tried updating that Spotify library to the newer version in the latest release 3.2.0 (https://github.com/mitchhymel/MusicBeeSyncToService/releases/tag/3.2.0). Try getting 3.2.0 and see if that fixes the problem.

**Comment by scapehips** [comment]
It works now. Thanks for updating.
