### ISSUE TITLE
nothing happened after login

### ISSUE THREAD

**Issue by ALXRITR** [mitchhymel/MusicBeeSyncToService#6]
![Screenshot 2021-05-22 220922](https://user-images.githubusercontent.com/77064641/119239589-65832680-bb4a-11eb-9c54-6bfe6978a3db.jpg)

Nothing happening after Login. But get the Message in the Browser, that the operation was seccessfull

**Comment by ALXRITR** [comment]
Dont know how, but helped to overwrite the files with the newest release (3.2.0) maybe because i already had an MB-Plugin for Spotify (another from the Forum).
Anyway=> THX SO MUCH. Saved me so much work with looking up every single song and add it to my Playlist. U DA BEST BOII

**Comment by mitchhymel** [comment]
Happy to hear you were able to solve your problem and the plugin helped you. Thanks!
